container:
  # we're using this because it includes sbt in the image.
  image: circleci/openjdk:8
  cpu: 2
  memory: 2

test_task:
  test_script: sbt test scripted
  scalafmt_script: sbt scalafmtCheckAll

